extends:
  - plugin:@next/next/core-web-vitals
  - xo
  - xo-typescript
  - xo-react
  - plugin:react/jsx-runtime # Prevents "'React' must be in scope when using JSX" errors
  - plugin:tailwindcss/recommended
  - prettier
  - turbo

# parserOptions:
#   babelOptions:
#     presets:
#       - next/babel

rules:
  '@next/next/no-html-link-for-pages': 'off'
  'tailwindcss/classnames-order': 'off' # Handled by "prettier-plugin-tailwindcss"

settings:
  tailwindcss:
    config: tailwind.config.ts
